<a href="https://colab.research.google.com/github/andrewdk1123/KoSentiment/blob/main/data/RENN%20Undersampler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Load Packages

In [1]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 138 (delta 26), reused 22 (delta 8), pack-reused 91
Receiving objects: 100% (138/138), 1.72 MiB | 19.30 MiB/s, done.
Resolving deltas: 100% (65/65), done.


In [2]:
ls

Mecab-ko-for-Google-Colab/  sample_data/


In [3]:
cd Mecab-ko-for-Google-Colab

/content/Mecab-ko-for-Google-Colab


In [4]:
!bash install_mecab-ko_on_colab_light_220429.sh

Installing konlpy.....
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 76.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 45.4 MB/s eta 0:00:00
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2023-12-08 08:38:32--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22cd:e0db
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None&AWSAccessKeyId=ASIA6KOSE3BNFKD2JKVZ&Signature=gCkrVeZqJ3xExQkzomdCcoetyIM%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEFEaCXVzLWVhc3QtMSJGMEQCIEBvH4

In [5]:
from konlpy.tag import Okt

okt = Okt()
text = u"""이제 구글 코랩에서 Mecab-ko라이브러리 사용이 가능합니다. 읽어주셔서 감사합니다."""
nouns = okt.nouns(text)
print(nouns)

['이제', '구글', '코랩', '라이브러리', '사용']


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from imblearn.under_sampling import RepeatedEditedNearestNeighbours
import numpy as np
import matplotlib.pyplot as plt
import csv

# Upload Train Data

In [7]:
from google.colab import files

uploaded = files.upload()

Saving combined_train_data.csv to combined_train_data.csv


In [8]:
# Get the content of the uploaded file
file_content = next(iter(uploaded.values()))

# Convert bytes to string
file_content_str = file_content.decode('utf-8')

labels = []
sentences = []

lines = file_content_str.split('\r\n')

header = lines[0].split('\t')
start_index = 1 if len(header) > 1 else 0

# Iterate through each line in the file
for line in lines[start_index:]:
    columns = line.split('\t')
    if len(columns) > 1:
        labels.append(columns[0])
        sentences.append(columns[1])

print(len(sentences))

57764


In [9]:
print("Labels:", labels[:10])
print("Sentences:", sentences[:10])

Labels: ['0', '0', '0', '0', '0', '0', '0', '1', '0', '1']
Sentences: ['일은 왜 해도 해도 끝이 없을까? 화가 난다.', '이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.', '회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스트레스 받아. ', '직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 섭섭해.', '얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.', '직장에 다니고 있지만 시간만 버리는 거 같아. 진지하게 진로에 대한 고민이 생겨.', '성인인데도 진로를 아직도 못 정했다고 부모님이 노여워하셔. 나도 섭섭해.', '퇴사한 지 얼마 안 됐지만 천천히 직장을 구해보려고.', '졸업반이라서 취업을 생각해야 하는데 지금 너무 느긋해서 이래도 되나 싶어.', '요즘 직장생활이 너무 편하고 좋은 것 같아!']


# Get Distances between Sentences

In [10]:
def calculate_ngram_distance(sentences, n=2, chunk_size=28):
    # Tokenize Korean sentences into n-grams using Okt from konlpy
    okt = Okt()
    tokenized_sentences = [' '.join(okt.nouns(sentence)) for sentence in sentences]

    # Tokenize sentences into n-grams
    vectorizer = CountVectorizer(analyzer=lambda x: x)
    ngram_matrix = vectorizer.fit_transform(tokenized_sentences).toarray()

    # Release memory after using Okt and vectorizer
    del okt
    del vectorizer

    # Get cosine similarity between n-gram representations
    distance_matrix = cosine_similarity(ngram_matrix)

    # Release memory after calculating cosine similarity
    del ngram_matrix

    # Calculate distance (1 - cosine similarity) through batches
    for i in range(0, len(sentences), chunk_size):
        sentence_batch = sentences[i:i+chunk_size]
        distance_matrix[i:i+chunk_size, i:i+chunk_size] = 1 - distance_matrix[i:i+chunk_size, i:i+chunk_size]

    return distance_matrix

In [11]:
test_examples = sentences[:3]
test_result = calculate_ngram_distance(test_examples, 2)

print("Bi-gram Similarity Matrix:")
print(test_result)

Bi-gram Similarity Matrix:
[[ 1.11022302e-16  2.34337087e-01  3.09232397e-01]
 [ 2.34337087e-01 -4.44089210e-16  2.76290529e-01]
 [ 3.09232397e-01  2.76290529e-01  0.00000000e+00]]


In [12]:
type(test_result)

numpy.ndarray

In [13]:
distance_matrix = calculate_ngram_distance(sentences)
print(distance_matrix.shape)

(57764, 57764)


In [14]:
distance_matrix[:3, :3]

array([[0.        , 0.23433709, 0.3092324 ],
       [0.23433709, 0.        , 0.27629053],
       [0.3092324 , 0.27629053, 0.        ]])

In [16]:
# Get the memory size of the array in bytes
memory_size_bytes = distance_matrix.nbytes

# Convert bytes to megabytes
memory_size_mb = memory_size_bytes / 1e6

# Print the memory size
print(f"Memory size of the numpy array: {memory_size_mb:.2f} MB")

Memory size of the numpy array: 26693.44 MB


In [15]:
!free

               total        used        free      shared  buff/cache   available
Mem:        53474512    27755572    20433740        1496     5285200    25134980
Swap:              0           0           0


## Train RENN Undersampler

In [ ]:
k_neighbors = 28  # Number of neighbors to consider for RENN
renn = RepeatedEditedNearestNeighbours(n_neighbors=k_neighbors)
undersampled_indices = renn.fit_resample(distance_matrix, labels)[1]

In [ ]:
# Extract the corresponding sentences based on the selected indices
undersampled_labels = [labels[i] for i in undersampled_indices]
undersampled_sentences = [sentences[i] for i in undersampled_indices]

undersampled_data = list(zip(undersampled_labels, undersampled_sentences))
csv_file_name = "undersampled_data.csv"

with open(csv_file_name, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(['emotion', 'sentence'])
    csv_writer.writerows(undersampled_data)

In [ ]:
files.download(csv_file_name)