<a href="https://colab.research.google.com/github/andrewdk1123/KoSentiment/blob/main/data/Tomek%20Link%20Undersampler%20based%20on%20N-gram%20Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install and Load Packages

In [2]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 138 (delta 26), reused 22 (delta 8), pack-reused 91
Receiving objects: 100% (138/138), 1.72 MiB | 33.14 MiB/s, done.
Resolving deltas: 100% (65/65), done.


In [3]:
ls

Mecab-ko-for-Google-Colab/  sample_data/


In [4]:
cd Mecab-ko-for-Google-Colab

/content/Mecab-ko-for-Google-Colab


In [5]:
!bash install_mecab-ko_on_colab_light_220429.sh

Installing konlpy.....
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 45.1 MB/s eta 0:00:00
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2023-12-10 09:02:36--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22cd:e0db
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None&AWSAccessKeyId=ASIA6KOSE3BNPDXC24WT&Signature=Lfczqa6DlVyJ%2Bk%2BO8hByL9waNZQ%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEIH%2F%2F%2F%2F%2F%2F%2F%2

In [6]:
from konlpy.tag import Okt

okt = Okt()
text = u"""이제 구글 코랩에서 Mecab-ko라이브러리 사용이 가능합니다. 읽어주셔서 감사합니다."""
nouns = okt.nouns(text)
print(nouns)

['이제', '구글', '코랩', '라이브러리', '사용']


In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from imblearn.under_sampling import TomekLinks
from collections import Counter
import numpy as np
import csv

# Upload Train Data

In [8]:
from google.colab import files

uploaded = files.upload()

Saving combined_train_data.csv to combined_train_data.csv


In [9]:
# Get the content of the uploaded file
file_content = next(iter(uploaded.values()))

# Convert bytes to string
file_content_str = file_content.decode('utf-8')

labels = []
sentences = []

lines = file_content_str.split('\r\n')

header = lines[0].split('\t')
start_index = 1 if len(header) > 1 else 0

# Iterate through each line in the file
for line in lines[start_index:]:
    columns = line.split('\t')
    if len(columns) > 1:
        labels.append(columns[0])
        sentences.append(columns[1])

print(len(sentences))

57754


In [10]:
print("Labels:", labels[:10])
print("Sentences:", sentences[:10])

Labels: ['0', '0', '0', '0', '0', '0', '0', '1', '0', '1']
Sentences: ['일은 왜 해도 해도 끝이 없을까? 화가 난다.', '이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.', '회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스트레스 받아. ', '직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 섭섭해.', '얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.', '직장에 다니고 있지만 시간만 버리는 거 같아. 진지하게 진로에 대한 고민이 생겨.', '성인인데도 진로를 아직도 못 정했다고 부모님이 노여워하셔. 나도 섭섭해.', '퇴사한 지 얼마 안 됐지만 천천히 직장을 구해보려고.', '졸업반이라서 취업을 생각해야 하는데 지금 너무 느긋해서 이래도 되나 싶어.', '요즘 직장생활이 너무 편하고 좋은 것 같아!']


# Get Distances between Sentences

아래의 함수는 n-gram 유사도를 기반으로 문장 간의 거리를 계산합니다. 함수는 다음과 같은 과정을 통해 각 문장간의 거리를 계산합니다.

1. 토큰화: `Konlpy`의 `Okt.nouns`를 활용하여 각 문장에서 명사를 추출합니다. 이후, 추출된 명사들을 공백으로 연결하여, 명사 토큰만을 포함한 문장 목록을 작성합니다. 이 작업은 각 문장의 감정을 표현하는 토큰이 명사에 주로 속해 있을 것이라는 가정을 기반으로 합니다
2. 거리 계산: `(문장 수) x (문장 수)` 거리 매트릭스를 만듭니다. 이 때, 메모리 문제를 피하기 위해 `chunk_size`를 사용하여 배치 단위로 문장을 반복합니다. 각 Batch의 토큰화된 문장을 이용하여 n-gram 빈도 매트릭스를 만들고, 매트릭스의 n-gram 벡터 사이의 코사인 유사도를 계산합니다. 이후, `1 - 코사인 유사도`를 계산하여 현재 Batch의 거리 매트릭스를 얻습니다.
3. 현재 Batch의 거리 매트릭스의 인덱스를 조정하여 전역 거리 매트릭스의 위치와 일치시키고, 이를 적절한 구역에 추가합니다.

이러한 과정을 통해 반환된 매트릭스의 각 요소는 두 문장간의 쌍별 거리를 나타냅니다.

In [11]:
def calculate_ngram_distance(sentences, n=2, chunk_size=28877):
    # Tokenize Korean sentences into n-grams using Okt from konlpy
    okt = Okt()
    tokenized_sentences = [' '.join(okt.nouns(sentence)) for sentence in sentences]

    # Calculate distance (1 - cosine similarity) through batches
    num_sentences = len(sentences)
    distance_matrix = np.zeros((num_sentences, num_sentences))

    for i in range(0, num_sentences, chunk_size):
        sentence_batch = sentences[i:i+chunk_size]
        tokenized_batch = tokenized_sentences[i:i+chunk_size]

        # Tokenize sentences into n-grams
        vectorizer = CountVectorizer(analyzer=lambda x: x)
        ngram_matrix = vectorizer.fit_transform(tokenized_batch).toarray()
        batch_distance_matrix = cosine_similarity(ngram_matrix)

        # Adjust the indices for the global distance matrix
        start_idx = i
        end_idx = min(i + chunk_size, num_sentences)
        distance_matrix[start_idx:end_idx, start_idx:end_idx] = 1 - batch_distance_matrix

    return distance_matrix

In [12]:
test_examples = sentences[-3:]
test_result = calculate_ngram_distance(test_examples)

print("Bi-gram Similarity Matrix:")
print(test_result)

Bi-gram Similarity Matrix:
[[-4.44089210e-16  8.72362172e-02  1.31331517e-01]
 [ 8.72362172e-02  8.88178420e-16  1.04980952e-01]
 [ 1.31331517e-01  1.04980952e-01 -6.66133815e-16]]


In [13]:
type(test_result)

numpy.ndarray

In [14]:
distance_matrix = calculate_ngram_distance(sentences)
print(distance_matrix.shape)

(57754, 57754)


In [15]:
distance_matrix[-3:, -3:]

array([[ 0.00000000e+00,  8.72362172e-02,  1.31331517e-01],
       [ 8.72362172e-02,  0.00000000e+00,  1.04980952e-01],
       [ 1.31331517e-01,  1.04980952e-01, -4.44089210e-16]])

# Tomek Link Undersampler

언더샘플링을 진행하기 전 Raw Data `label`의 분포는 다음과 같습니다.

In [17]:
# Count class distribution before undersampling
counter = Counter(labels)
print("Original class distribution:", counter)

Original class distribution: Counter({'0': 45502, '1': 12252})


앞서 계산한 거리 매트릭스를 이용하여 Tomek Link Undersampling을 수행합니다. Tomek Link는 다음 조건을 만족하는 두 점 (i, j)의 쌍입니다.

 * i는 자기 자신을 제외한 데이터셋의 다른 모든 점보다 j에 더 가깝습니다.
 * j는 자기 자신을 제외한 데이터셋의 다른 모든 점보다 i에 더 가깝습니다.

즉, Tomek 링크는 자기 자신을 제외한 가장 가까운 문장이 어떤 것인지를 반환합니다. 여기서 Tomek Link Undersampling은 발견한 Tomek Link 중에서 서로 Label이 다른 케이스를 제거하는 식으로 진행됩니다. 따라서 Undersampled Dataset에는 거리가 가까운 문장들 (비슷한 명사를 가진 문장들) 중에서 서로 다른 Label 값을 갖는 경우를 삭제함으로써 데이터의 이상치를 제거하고 Imbalanced Classification 문제를 완화할 수 있습니다.

In [28]:
tl = TomekLinks()
indices_before_resampling = np.arange(len(labels))  # Keep track of original indices
X_resampled, y_resampled = tl.fit_resample(distance_matrix, labels)
indices_after_resampling = np.arange(len(y_resampled))  # New indices after resampling

Tomek Link Undersampling을 수행한 이후의 Class 분포는 다음과 같습니다.

In [29]:
counter = Counter(y_resampled)
print("Resampled class distribution:", counter)

Resampled class distribution: Counter({'0': 43549, '1': 12252})


Undersampling을 통해 삭제된 문장들의 갯수는 아래와 같습니다.

In [33]:
# Find the indices that were removed
indices_removed = np.setdiff1d(indices_before_resampling, indices_after_resampling)
print(len(indices_removed))

1953


Undersampling 이후 남은 문장들의 갯수는 아래와 같습니다.

In [34]:
# Find the indices that were kept
indices_kept = np.setdiff1d(indices_before_resampling, indices_removed)
print(len(indices_kept))

55801


추출된 문장들을 CSV 형태로 다운로드 하겠습니다.

In [35]:
undersampled_sentences = [sentences[i] for i in indices_kept]
undersampled_labels = [labels[i] for i in indices_kept]

In [36]:
csv_file_name = 'undersampled_training.csv'
undersampled_data = list(zip(undersampled_labels, undersampled_sentences))

# Write and download the undersampled data as a CSV file
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['emotion', 'sentences'])
    writer.writerows(undersampled_data)

print(f'The data has been written to {csv_file_name}.')

files.download(csv_file_name)


The data has been written to undersampled_training.csv.


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>